// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "lvgl.h"

void ui_Screen1_screen_init (void);
lv_obj_t* ui_Screen1;
lv_obj_t* ui_Calendar1;
lv_obj_t* ui_Label2;

void ui_Screen1_screen_init (void)
{
    ui_Calendar1 = lv_calendar_create (lv_scr_act ());
    lv_obj_t* ui_Calendar1_header = lv_calendar_header_arrow_create (ui_Calendar1);
    lv_obj_set_width (ui_Calendar1, 230);
    lv_obj_set_height (ui_Calendar1, 240);
    lv_obj_set_x (ui_Calendar1, 0);
    lv_obj_set_y (ui_Calendar1, 38);
    lv_obj_set_align (ui_Calendar1, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create (lv_scr_act ());
    lv_obj_set_width (ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height (ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x (ui_Label2, -7);
    lv_obj_set_y (ui_Label2, -129);
    lv_obj_set_align (ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text (ui_Label2, "Calendar test");

}
